import { MoreOutlined, MessageOutlined } from "@ant-design/icons";

 export const notifications = [
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "10 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "13 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "15 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "23 min ago",
  },
  {
    notification_icon: <MessageOutlined />,
    notification_title: "Lorem ipsum dolor sit amet.",
    notification_subtitle: "At vero eos et accusam et justo duo dolores ete.",
    notification_time: "30 min ago",
  },
];
